grafana:
  enabled: true
  adminPassword: admin
  service:
    type: NodePort
    nodePorts:
      http: 30080

prometheus:
  prometheusSpec:
    retention: 24h
  service:
    type: NodePort
    nodePort: 30090

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

kube-state-metrics:
  metricLabelsAllowlist:
    - "pods=[zone,role,scenario,app]"
